name: telegram message
on: [push, pull_request]
jobs:
    notify:
        name: Notify on Push, Pull Request
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Get changed files
              id: changed-files
              uses: tj-actions/changed-files@v44

            - name: Generate changed files message
              id: generate-changed-files-message
              run: |
                  generate_message() {
                    local files="$1"
                    local added=""
                    local modified=""
                    local deleted=""
                    for file in $files; do
                      status=$(git diff --name-status HEAD~1 $file | awk '{print $1}')
                      case "$status" in
                        A)
                          added+="$file\n"
                          ;;
                        M)
                          modified+="$file\n"
                          ;;
                        D)
                          deleted+="$file\n"
                          ;;
                      esac
                    done

                    message="*Changed Files:*\n"
                    if [ -n "$added" ]; then
                      message+="🟢 *Added:*\n$added\n"
                    fi
                    if [ -n "$modified" ]; then
                      message+="🟡 *Modified:*\n$modified\n"
                    fi
                    if [ -n "$deleted" ]; then
                      message+="🔴 *Deleted:*\n$deleted\n"
                    fi

                    echo "CHANGED_FILES_MESSAGE<<EOF" >> $GITHUB_ENV
                    echo "$message" >> $GITHUB_ENV
                    echo "EOF" >> $GITHUB_ENV
                  }

                  generate_message "${{ steps.changed-files.outputs.all_changed_files }}"

            - name: Send Telegram message on push
              if: github.event_name == 'push'
              uses: appleboy/telegram-action@master
              with:
                  to: ${{ secrets.TELEGRAM_TO }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  format: markdown
                  message: |
                      *New Push Notification*
                      🔹 *Repository:* `${{ github.repository }}`
                      🔹 *Pushed by:* `${{ github.actor }}`
                      🔹 *Pushed to:* `${{ github.ref_name }}`
                      🔹 *Commit message:* `${{ github.event.head_commit.message }}`
                      🔗 View Commit: [Commit Link](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
                      🔗 View Commits History: [Commits History Link](https://github.com/${{ github.repository }}/commits/${{ github.ref_name }})
                      ${{ env.CHANGED_FILES_MESSAGE }}

            - name: Send Telegram message on pull request
              if: github.event_name == 'pull_request'
              uses: appleboy/telegram-action@master
              with:
                  to: ${{ secrets.TELEGRAM_TO }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  format: markdown
                  message: |
                      *New Pull Request Notification*
                      🔹 *Repository:* `${{ github.repository }}`
                      🔹 *Title:* `${{ github.event.pull_request.title }}`
                      🔹 *Author:* `${{ github.event.pull_request.user.login }}`
                      🔹 *Description:*
                      `${{ github.event.pull_request.body }}`
                      [View Pull Request](${ { github.event.pull_request.html_url }})
                      ${{ env.CHANGED_FILES_MESSAGE }}

            - name: Send Telegram message on stage commit
              if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/stage')
              uses: appleboy/telegram-action@master
              with:
                  to: ${{ secrets.TELEGRAM_TO }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  format: markdown
                  message: |
                      *New Stage Commit Notification*
                      🔹 *Repository:* `${{ github.repository }}`
                      🔹 *Pushed by:* `${{ github.actor }}`
                      🔹 *Pushed to stage branch:* `${{ github.ref_name }}`
                      🔹 *Commit message:* `${{ github.event.head_commit.message }}`
                      🔗 View Commit: [Commit Link](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
                      ${{ env.CHANGED_FILES_MESSAGE }}
